### ISSUE TITLE
requests.exceptions.MissingSchema Error

### ISSUE THREAD

**Issue by pushshift** [mediacloud/feed_seeker#6]
When scanning www.nytimes.org (spider level 2), after discovery of http://takingnote.blogs.nytimes.com/feed, the script errors out with a missing schema error. It appears the script is making a request for a url without including the schema (http/https).

> Traceback (most recent call last):
>   File "./scan_feeds.py", line 7, in <module>
>     for url in generate_feed_urls('http://www.nytimes.com',spider=2):
>   File "/usr/local/lib/python3.6/dist-packages/feed_seeker/feed_seeker.py", line 420, in generate_feed_urls
>     for feed in FeedSeeker(url, html).generate_feed_urls(spider=spider, max_links=max_links):
>   File "/usr/local/lib/python3.6/dist-packages/feed_seeker/feed_seeker.py", line 200, in generate_feed_urls
>     for url, _ in self._generate_feed_urls(spider=spider, max_links=max_links):
>   File "/usr/local/lib/python3.6/dist-packages/feed_seeker/feed_seeker.py", line 252, in _generate_feed_urls
>     for url, seen in spider_seeker._generate_feed_urls(**kwargs):
>   File "/usr/local/lib/python3.6/dist-packages/feed_seeker/feed_seeker.py", line 252, in _generate_feed_urls
>     for url, seen in spider_seeker._generate_feed_urls(**kwargs):
>   File "/usr/local/lib/python3.6/dist-packages/feed_seeker/feed_seeker.py", line 227, in _generate_feed_urls
>     if not self.html:
>   File "/usr/local/lib/python3.6/dist-packages/feed_seeker/feed_seeker.py", line 152, in html
>     self._html = self.fetcher(self.url)
>   File "/usr/local/lib/python3.6/dist-packages/feed_seeker/feed_seeker.py", line 104, in default_fetch_function
>     response = session.get(url)
>   File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 546, in get
>     return self.request('GET', url, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 519, in request
>     prep = self.prepare_request(req)
>   File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 462, in prepare_request
>     hooks=merge_hooks(request.hooks, self.hooks),
>   File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 313, in prepare
>     self.prepare_url(url, params)
>   File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 387, in prepare_url
>     raise MissingSchema(error)
> requests.exceptions.MissingSchema: Invalid URL '//www.nytimes.com/2017/01/10/watching/faq.html': No schema supplied. Perhaps you meant http:////www.nytimes.com/2017/01/10/watching/faq.html

**Comment by pushshift** [comment]
Fix: https://github.com/mitmedialab/feed_seeker/commit/989ae5a55ba8d7f196c24fecfa1b80833b110395

**Comment by pushshift** [comment]
https://github.com/mitmedialab/feed_seeker/commit/989ae5a55ba8d7f196c24fecfa1b80833b110395
